name: Vercel Preview Deployment

env:
   VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
   VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
   push:
      branches-ignore: [main]

   pull_request:
      branches-ignore: [main]


jobs:
   Deploy:
      runs-on: ubuntu-latest
      env: 
         API_KEY: ${{ secrets.API_KEY }}   
         BASE_URL: ${{ vars.BASE_URL }}

      strategy:
         matrix:
           node-version: [22.x]

      steps:
         - name: Checkout code
           uses: actions/checkout@v4

         - name: Setup Node.js
           uses: actions/setup-node@v4
           with:
              node-version: ${{ matrix.node-version }}

         - name: Install weather-app dependencies
           run: |
              cd weather-app
              npm ci

         - name: Run ESLint (weather-app)
           run: |
              cd weather-app
              npm run lint

         - name: Run tests (weather-app)
           run: |
              cd weather-app
              npm test

         - name: Install Vercel CLI
           run: npm install --global vercel

         - name: Pull Vercel Environment Information
           run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

         - name: Build Project Artifacts
           run: |
              vercel build --token=${{ secrets.VERCEL_TOKEN }}

         - name: Deploy Project Artifacts
           run: |
              vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
